//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAssigment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public long Key { get; set; }
        public int Status { get; set; }
        public System.DateTime ExpiredTime { get; set; }
        public int CustID { get; set; }
    
        public virtual User User { get; set; }
    }
}
