//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAssigment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int Id { get; set; }
        public string Line1 { get; set; }
        public string Line2 { get; set; }
        public string City { get; set; }
        public Nullable<int> Postcode { get; set; }
        public string States { get; set; }
        public string Country { get; set; }
        public Nullable<bool> Default { get; set; }
        public int CustID { get; set; }
    
        public virtual User User { get; set; }
    }
}
